First Release of DDQ Backend Mock
tests-always-included/ddq-backend-mock pull request #1
Opened 2016-09-22 20:01 UTC by AbsentSemicolon

Sets up having a mock for providing DDQ and example for further implementation and how a backend could work.

2016-09-23 12:15 UTC, lnagle93 commented on lib/ddq-backend-mock.js
> +         * Starts polling for data. If data isfound it emits "data" so DDQ knows
Need a space in 'isfound'.

2016-09-23 12:18 UTC, lnagle93 commented on package.json
> +}
Indentation is off throughout.

2016-09-23 17:07 UTC, fidian commented on lib/ddq-backend-mock.js
> +            var file, files, keys;
Not really files.

2016-09-23 17:09 UTC, fidian commented on lib/ddq-backend-mock.js
> +                        requeue: requeue.bind(null, this, file.id)
On remove or requeue, make sure to do another immediate poll.  Only one needs to be sent at that time, not all of them.

2016-09-23 17:11 UTC, fidian commented on lib/ddq-backend-mock.js
> +            keys = Object.keys(files);
I would suggest filtering the keys to eliminate entries that are being processed.

We think that the data store should be a Map, not an Object.

2016-09-23 17:13 UTC, fidian commented on lib/ddq-backend-mock.js
> +                    this.writeRecord(file);
You're dealing with objects.  Be careful.  The line above already did what you wanted.

2016-09-23 17:13 UTC, fidian commented on lib/ddq-backend-mock.js
> +            this.poller = timers.setInterval(() => {
No, not intervals!  Aaahahhhahaa!

2016-09-23 17:15 UTC, fidian commented on lib/ddq-backend-mock.js
> +                this.writeRecord(finalMessage);
Note, this STAYS but you could just replace this line with `files[finalMessage.id] = finalMessage`;

2016-09-23 17:16 UTC, fidian commented on package.json
> +  "private": false,
Drop this line

2016-09-23 17:16 UTC, fidian commented on package.json
> +    "ddq": "git://github.com/AbsentSemicolon/ddq.git#release-1"
Drop

2016-09-23 17:18 UTC, fidian commented on package.json
> +    "node": "*"
Isn't this >=4

2016-09-23 17:20 UTC, fidian requested changes

2016-09-23 17:20 UTC, fidian commented on .eslintrc.yaml
> +    - eslint:recommended
Change to

   -
        eslint: recommended

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +1. Fork the repo. There is a very simple way of doing this on GitHub.
Link to alternate documentation, especially GitHub's documentation.  Do not write it up here.

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +3. Create a branch off master `git checkout -b <branch name>`. You don't want to do any work off master as this is where you will pull in upstream changes and merge them into your branches. Also is a
"2", not "3"

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +4. Write your code as normal.  Be sure to follow the [Tests-Always-Included Style Guide](https://tests-always-included.github.io/style-guide/)
"3", not "4".

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +Before creating a pull request it's a good idea to pull in the upstream changes, just in case someone has created a Pull Request before you and it has been merged in.
Pull Request is not a Proper Noun and We don't really prefer to speak like Winnie the Pooh.

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +## Pull Requests
This does not need a separate section.  Omit this line.

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +1. Checkout the master branch `git checkout master`.
Can we just link somewhere instead of writing these instructions up all the time?

2016-09-23 17:20 UTC, fidian commented on CONTRIBUTING.md
> +6. We suggest squashing commits, if able, and creating a Pull Request on GitHub, but this has been problematic when merge conflicts have been present. The other way is to create a patch. Follow the i
Not necessary, I'll happily squash them for you.  Plus we can link somewhere.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> + * @typeDef {Object} DdqBackend~record
Lowercase d

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> + * @property {Function} heartbeatKill
Delete me.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +                callback(this.instanceId);
The callback should be a standard Node-style callback, with an optional error as the first parameter.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +    function heartbeatKill(ddqBackendInstance, recordId) {
This should not exist.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +                    this.instanceId = id.toString("hex");
If we are using an in-memory data store, why do we care about the instance ID?  This additional complexity should be removed.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +         * Gets the stored data or a particular one beind searched for.
The second half of the sentence is not reflected in the code below.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +            record = ddqBackendInstance.getRecord(recordId);
What if this fails?

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> + * @property {(string|null)} heartbeatTime
This should just be a Date object.

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +                        heartbeatKill: heartbeatKill.bind(null, this.file.id),
Delete

2016-09-23 17:20 UTC, fidian commented on lib/ddq-backend-mock.js
> +                file = files[keys[keys.length * Math.random() << 0]];
Why bitwise shift?  Just to cast to an integer?

```
Math.floor(keys.length * Math.random())
```

However, I think you should just use a shuffle.  http://stackoverflow.com/questions/962802/is-it-correct-to-use-javascript-array-sort-method-for-shuffling  Then iterate over the list and emit ALL of the datas or until you're paused.
Maybe the poll amount (max number tried) could be another config option that could match the max number being processed?

2016-09-26 18:48 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +         * Starts polling for data. If data isfound it emits "data" so DDQ knows
Spaced

2016-09-26 18:51 UTC, AbsentSemicolon commented on package.json
> +}
Shouldn't let package.json do most of the indenting.

2016-09-26 18:52 UTC, AbsentSemicolon commented on .eslintrc.yaml
> +    - eslint:recommended
This is supposed to be a string so it needs to stay like that.

2016-09-26 18:53 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +1. Fork the repo. There is a very simple way of doing this on GitHub.
Added a link to Githubs doc on forking.

2016-09-26 18:54 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +3. Create a branch off master `git checkout -b <branch name>`. You don't want to do any work off master as this is where you will pull in upstream changes and merge them into your branches. Also is a
Think I took something out of here and didn't update the numbers.

2016-09-26 18:54 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +4. Write your code as normal.  Be sure to follow the [Tests-Always-Included Style Guide](https://tests-always-included.github.io/style-guide/)
Updated

2016-09-26 19:04 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> + * @typeDef {Object} DdqBackend~record
ok.

2016-09-26 19:04 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> + * @property {(string|null)} heartbeatTime
ok.

2016-09-26 19:05 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> + * @property {Function} heartbeatKill
Yep, gone.

2016-09-26 19:05 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +    function heartbeatKill(ddqBackendInstance, recordId) {
Removed

2016-09-26 20:27 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                    this.writeRecord(file);
Right, this shouldn't be there.

2016-09-26 20:27 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                        heartbeatKill: heartbeatKill.bind(null, this.file.id),
Deleted

2016-09-26 20:40 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +            this.poller = timers.setInterval(() => {
AHHHHH!!!! This has been replaced with setTimeout.

2016-09-26 20:41 UTC, AbsentSemicolon commented on package.json
> +    "ddq": "git://github.com/AbsentSemicolon/ddq.git#release-1"
Dropped

2016-09-26 20:41 UTC, AbsentSemicolon commented on package.json
> +    "node": "*"
Made it so we support node great or equal to 4.

2016-09-26 20:41 UTC, AbsentSemicolon commented on package.json
> +  "private": false,
Dropped

2016-09-26 20:41 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                this.writeRecord(finalMessage);
Yeah no need for write record if we are dealing with object we can just edit. We aren't protecting them or anything.

2016-09-26 20:42 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +         * Gets the stored data or a particular one beind searched for.
Was the original thought behind this function.

2016-09-27 16:11 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                        requeue: requeue.bind(null, this, file.id)
Making a call to get another message as soon as we requeue and remove.

2016-09-27 16:11 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +            var file, files, keys;
This uses records now.

2016-09-27 16:12 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                    this.instanceId = id.toString("hex");
Took out owner, not really needed.

2016-09-27 16:13 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                callback(this.instanceId);
This was taken out.

2016-09-27 16:20 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +            record = ddqBackendInstance.getRecord(recordId);
Sending error back as the front end is expecting.

2016-09-27 16:20 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +Before creating a pull request it's a good idea to pull in the upstream changes, just in case someone has created a Pull Request before you and it has been merged in.
Fixed.

2016-09-27 16:20 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +## Pull Requests
Took this out.

2016-09-27 17:10 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +                file = files[keys[keys.length * Math.random() << 0]];
Found a way to randomize the array and just pull the first one for processing. Also using map to populate an array with ones which are not processing.

2016-09-27 17:10 UTC, AbsentSemicolon commented on lib/ddq-backend-mock.js
> +            keys = Object.keys(files);
Made this a map.

2016-09-27 18:50 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +1. Checkout the master branch `git checkout master`.
Linked to an article about pulling in upstream changes.

2016-09-27 18:50 UTC, AbsentSemicolon commented on CONTRIBUTING.md
> +6. We suggest squashing commits, if able, and creating a Pull Request on GitHub, but this has been problematic when merge conflicts have been present. The other way is to create a patch. Follow the i
linked to an article about pull requests in Github.

2016-09-29 16:51 UTC, fidian approved these changes

2016-09-29 16:51 UTC, merged