Update naming conventions
tests-always-included/ddq-backend-mock pull request #10
Opened 2016-10-31 16:37 UTC by lnagle93

2016-10-31 16:47 UTC, fidian requested changes
It seems that `open()` is a helper method to simply start polling.  That should either be logic handled by the ddq core or eliminated entirely.

2016-10-31 16:47 UTC, fidian commented on lib/ddq-backend-mock.js
> +        open() {
Why does `open()` exist?

2016-10-31 16:49 UTC, GoogilyBoogily commented
The version bump isn't correct for what's being changed.

2016-10-31 16:50 UTC, GoogilyBoogily commented on package.json
> +    "version": "1.0.5"
The changes aren't backwards compatible, so the version bump isn't correct.

2016-10-31 17:27 UTC, lnagle commented on lib/ddq-backend-mock.js
> +        open() {
An oversight. Removed.

2016-10-31 17:27 UTC, lnagle commented on package.json
> +    "version": "1.0.5"
Fixed.

2016-11-01 20:23 UTC, AbsentSemicolon commented
Looks good to me.

2016-11-01 22:03 UTC, GoogilyBoogily commented
Looks good to me also.

2016-11-03 12:31 UTC, fidian approved these changes

2016-11-03 12:32 UTC, merged